# examples/rising_bubble_2d
NTYPES=6
TWODIMS
GAMMA=1.66666666666666
VORONOI
REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED
REGULARIZE_MESH_FACE_ANGLE
#TREE_BASED_TIMESTEPS # off
DOUBLEPRECISION=1
OUTPUT_IN_DOUBLEPRECISION # snapshot files will be written in double precision
INPUT_IN_DOUBLEPRECISION  # initial conditions are in double precision

# generic
VORONOI_DYNAMIC_UPDATE
HAVE_HDF5
#DEBUG

MESHRELAX_DENSITY_IN_INPUT
OUTPUT_CENTER_OF_MASS

MHD
RIEMANN_HLLD
MHD_POWELL


TETRA_INDEX_IN_FACE
VORONOI_MESH_KEEP_DT_AND_DTC


TREE_BASED_TIMESTEPS
# BOUNDARY_REFL_FLUIDSIDE_MINID=1000000001
# BOUNDARY_REFL_FLUIDSIDE_MAXID=1100000000
# BOUNDARY_REFL_SOLIDSIDE_MINID=1100000001
# BOUNDARY_REFL_SOLIDSIDE_MAXID=1200000000

BRAGINSKII_VISCOSITY
# BRAGINSKII_VISCOSITY_GLOBAL_TIMESTEP
BRAGINSKII_RKL2_SUPER_TIME_STEPPING
# BRAGINSKII_OUTPUT_PRESSURE_ANISOTROPY
BRAGINSKII_OUTPUT_NUM_SUBSTEPS
OUTPUT_TIMEBIN_HYDRO


GRAVITY_NOT_PERIODIC          # if gravity is not to be treated periodically
EXTERNALGRAVITY               # switch on for external potential
STATIC_ISOTHERMAL_CLUSTER

PASSIVE_SCALARS=1


BOUNDARY_REFL_FLUIDSIDE_MINID=10000001  # defines the ID ranges describing a reflective boundary
BOUNDARY_REFL_FLUIDSIDE_MAXID=30000000  # defines the ID ranges describing a reflective boundary
BOUNDARY_REFL_SOLIDSIDE_MINID=0
BOUNDARY_REFL_SOLIDSIDE_MAXID=10000000
