# examples/brag_2d
NTYPES=6
NSOFTTYPES=2
TWODIMS
GAMMA=1.66666666666666
VORONOI
REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED
REGULARIZE_MESH_FACE_ANGLE
#TREE_BASED_TIMESTEPS # off
DOUBLEPRECISION=1
OUTPUT_IN_DOUBLEPRECISION # snapshot files will be written in double precision
INPUT_IN_DOUBLEPRECISION  # initial conditions are in double precision

VORONOI_MESH_KEEP_DT_AND_DTC

# generic
VORONOI_DYNAMIC_UPDATE
HAVE_HDF5
#DEBUG


FORCE_EQUAL_TIMESTEPS
# LONG_Y=0.125 # Nx=32
# LONG_Y=0.0625 # Nx=64
LONG_Y=0.03125 # Nx=128
# LONG_Y=0.015625 # Nx=256
# LONG_Y=0.0078125 # Nx=512
# LONG_Y=0.005 # Nx=800
# LONG_Y=0.00390625 # Nx=1024
# LONG_Y=0.001953125 # Nx=2048

# VISCOSITY
# USE_KINEMATIC_VISCOSITY
# THERMAL_CONDUCTION

# TRACER_FIELD
# TRACER_DIFFUSION

#IMPOSE_PINNING

# VORONOI_STATIC_MESH

MESHRELAX_DENSITY_IN_INPUT

OUTPUT_CENTER_OF_MASS

MHD
RIEMANN_HLLD

# MHD_CT
# MHD_CT_IC=0
TETRA_INDEX_IN_FACE
# MHD_POWELL
# MHD_POWELL_LIMIT_TIMESTEP

# MHD_SEEDFIELD

NOHYDRO
NOHYDRO_NOTIMESTEP

BRAGINSKII_VISCOSITY
BRAGINSKII_VISCOSITY_GLOBAL_TIMESTEP
TREE_BASED_TIMESTEPS

#BRAGINSKII_SIMPLE_DERIVATIVES

BRAGINSKII_RKL2_SUPER_TIME_STEPPING
# BRAGINSKII_LIMIT_PRESSURE_ANISOTROPY
BRAGINSKII_OUTPUT_PRESSURE_ANISOTROPY
