# examples/shocktube/shocktube_sod_1d

NTYPES=6
NSOFTTYPES=2
ONEDIMS
LONG_X=10.0
REFLECTIVE_X=1
GAMMA=1.4
VORONOI
REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED
REGULARIZE_MESH_FACE_ANGLE
DOUBLEPRECISION=1
OUTPUT_PRESSURE

# generic
VORONOI_DYNAMIC_UPDATE
HAVE_HDF5
DEBUG
