# examples/AMR/shocktube_2d

NTYPES=6
TWODIMS
LONG_X=0.25
GAMMA=1.4

AMR
AMR_GRADIENTS
#AMR_CONNECTIONS
FORCE_EQUAL_TIMESTEPS
NO_GAS_SELFGRAVITY

DOUBLEPRECISION=1
DOUBLEPRECISION_FFTW
OUTPUT_IN_DOUBLEPRECISION
INPUT_IN_DOUBLEPRECISION

OUTPUT_PRESSURE_GRADIENT
OUTPUT_DENSITY_GRADIENT
OUTPUT_VELOCITY_GRADIENT
OUTPUT_SURFACE_AREA
OUTPUT_PRESSURE

# generic
CHUNKING
HAVE_HDF5
DEBUG

# Config.sh
UNLIMITED_GRADIENTS

# Config_albada.sh
#UNLIMITED_GRADIENTS
#TVD_SLOPE_LIMITER
#TVD_SLOPE_LIMITER_ALBADA

# Config_arepo.sh

# Config_minbee.sh
#UNLIMITED_GRADIENTS
#TVD_SLOPE_LIMITER
#TVD_SLOPE_LIMITER_MINBEE

# Config_superbee.sh
#TVD_SLOPE_LIMITER
#TVD_SLOPE_LIMITER_SUPERBEE

# Config_vanleer.sh
#TVD_SLOPE_LIMITER2
#TVD_SLOPE_LIMITER_VANLEER
