# examples/ForceLawTests/TreePMWithHighResRegion

NTYPES=6
IMPOSE_PINNING
EVALPOTENTIAL
SELFGRAVITY
PMGRID=128
FORCETEST=1.0
FORCETEST_TESTFORCELAW=2
RCUT=8.0
ASMTH=2.0
DOUBLEPRECISION=1
DOUBLEPRECISION_FFTW
HAVE_HDF5
DEBUG
VORONOI
VORONOI_DYNAMIC_UPDATE
PLACEHIGHRESREGION=4
ENLARGEREGION=1.01

#ALLOW_DIRECT_SUMMATION
#DIRECT_SUMMATION_THRESHOLD=10000
